version: '3'
services:
  dataspace-connector:
    container_name: dsc-consumer
    build:
      context: ../../
      dockerfile: docker/app/Dockerfile
      args:
        ENV: ${NODE_ENV}
#    command: npm run dev
    restart: unless-stopped
    tty: true
    volumes:
      - '../../src/:/usr/src/app/src'
      - '../../config.json/:/usr/src/app/config.json'
    ports:
      - "3021:3000"
    links:
      - mongodb
    env_file:
      - .env
    networks:
      - dsc-consumer
      - consumer-api_consumer


  mongodb:
    container_name: "dsc-consumer-mongodb"
    build:
      context: ../../
      dockerfile: docker/mongodb/Dockerfile
    #    Uncomment to connect mongodb container to mongo compass or another service
    ports:
      - "27020:27017"
    volumes:
      - ./data:/data/db
    networks:
      - dsc-consumer

networks:
  dsc-consumer:
    external: false
  consumer-api_consumer:
    external: true